
package: doto

platform:
  - linux-64
  - osx-64

engine:
   - python=2
   - python=3

before_script:
  - python -V
  - conda install -q six requests pycrypto jinja2 setuptools

script: |
  conda build conda.recipe;
  echo `uname`;
  platform=`uname`;
  if [[ "$platform" == 'Linux' ]]; then
  mkdir -p /opt/anaconda/conda-bld/win-64;
  conda convert -p win-64 /opt/anaconda/conda-bld/linux-64/doto*.tar.bz2;
  filename=`ls win-64/doto*.tar.bz2 | xargs -n 1 basename`;
  echo $filename;
  cp -r win-64/$filename /opt/anaconda/conda-bld/win-64/$filename;
  fi;
  python -c 'import doto';
  python tests/test_gets.py;


## Build Targets: Upload these files to your binstar package
build_targets:
    files: /opt/anaconda/conda-bld/*/doto*.tar.bz2
    channels: 'main'
