
package: doto

platform:
  - linux-64

engine:
   - python=2
   - python=3

before_script:
  - python -V
  - conda install -q six requests pycrypto jinja2

script:
  - python setup.py install
  - python -c 'import doto';
  - python tests/test_gets.py
  - conda build conda.recipe
  - mkdir dist
  - cp `conda build conda.recipe --output` dist/


## Build Targets: Upload these files to your binstar package
build_targets:
  - dist/*
