package:
  name: doto
  version: 0.1.1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - requests
    - pandas
    - pycrypto

test:
  # Python imports
  imports:
    - doto

about:
  home: https://github.com/quasiben/doto
  license: BSD

